fix pseudo terminal issue

diff --git a/.github/workflows/maintenance_wbs_strato.yml b/.github/workflows/maintenance_wbs_strato.yml
--- a/.github/workflows/maintenance_wbs_strato.yml
+++ b/.github/workflows/maintenance_wbs_strato.yml
@@ -159,24 +159,24 @@ jobs:
           cd ${{ env.SSH_ROOT }}
           set -x
           if [ -f project-state.json ]; then
-            # Extract plugin names and statuses
-            PLUGIN_ENTRIES=$(grep -oP '"name": "\K[^"]+|(?<=status": ")(active|inactive)' project-state.json)
+              # Extract plugin names and statuses
+              PLUGIN_ENTRIES=$(grep -E '"name":|"status":' project-state.json | sed -E 's/.*"name": "(.*)",/\1/;s/.*"status": "(.*)"/\1/')
           
-            # Convert the entries into a list
-            PLUGIN_LIST=$(echo "$PLUGIN_ENTRIES" | paste -d'\n' - -)
-          
-            # Loop through each plugin and its status
-            while read -r PLUGIN_NAME; do
-              read -r PLUGIN_STATUS
-              if [ "$PLUGIN_STATUS" = "active" ]; then
-                wp plugin activate $PLUGIN_NAME --path=${{ env.SSH_ROOT }}/${{ inputs.wordpress_path }}
-              elif [ "$PLUGIN_STATUS" = "inactive" ]; then
-                wp plugin deactivate $PLUGIN_NAME --path=${{ env.SSH_ROOT }}/${{ inputs.wordpress_path }}
-              fi
-            done <<< "$PLUGIN_LIST"
+              # Convert the entries into a list
+              PLUGIN_LIST=$(echo "$PLUGIN_ENTRIES" | paste -d'\n' - -)
+            
+              # Loop through each plugin and its status
+              echo "$PLUGIN_LIST" | while read -r PLUGIN_NAME; do
+                  read -r PLUGIN_STATUS
+                  if [ "$PLUGIN_STATUS" = "active" ]; then
+                      wp plugin activate "$PLUGIN_NAME" --path="${env.SSH_ROOT}/${inputs.wordpress_path}"
+                  elif [ "$PLUGIN_STATUS" = "inactive" ]; then
+                      wp plugin deactivate "$PLUGIN_NAME" --path="${env.SSH_ROOT}/${inputs.wordpress_path}"
+                  fi
+              done
           else
-            echo "project-state.json file not found."
-            exit 1
+              echo "project-state.json file not found."
+              exit 1
           fi
           EOF
 
