refactoring actions

diff --git a/.github/workflows/maintenance_wb_maxcluster.yml b/.github/workflows/maintenance_wb_maxcluster.yml
--- a/.github/workflows/maintenance_wb_maxcluster.yml
+++ b/.github/workflows/maintenance_wb_maxcluster.yml
@@ -100,28 +100,23 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.ssh_private_key }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-
-      - name: 🔑 Ensure known_hosts file exists and set proper permissions
-        run: |
-          mkdir -p ~/.ssh
-          touch ~/.ssh/known_hosts
-          chmod 600 ~/.ssh/known_hosts
-
-      - name: ✈️ Save connection to known-hosts
-        run: |
-          ssh -o StrictHostKeyChecking=accept-new -T -i ~/.ssh/id_rsa ${{ secrets.ssh_user }}@${{ secrets.ssh_host }} true
-
-#      - name: 🔎 Check if remote folder exists
-#        run: |
-#          ssh -T -i ~/.ssh/id_rsa ${{ secrets.ssh_user }}@${{ secrets.ssh_host }} "[ -d ${{ env.SSH_ROOT }} ] && echo 'Directory exists' || echo 'Directory does not exist'"
+          ssh-keyscan -H ${{ secrets.ssh_host }} >> ~/.ssh/known_hosts
 
       - name: 💎 Checking rsync execution before upload
         run: |
-          rsync -avz --no-times -n --delete --include-from='.rsync-include' --exclude='*' ./ ${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ env.SSH_ROOT }}
+          rsync_output=$(rsync -avz -n --no-times --delete --include-from='.rsync-include' --exclude='*' ./ ${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ env.SSH_ROOT }} 2>&1)
+          rsync_exit_code=$?
+
+          echo "$rsync_output"
+
+          if [ $rsync_exit_code -ne 0 ]; then
+          echo "Error: Rsync encountered an error during the dry run."
+          exit 1
+          fi
 
       - name: 🌊 Upload files with rsync
         run: |
-          rsync -e 'ssh -o StrictHostKeyChecking=yes -T' -avz --no-times --delete --include-from='.rsync-include' --exclude='*' ./ ${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ env.SSH_ROOT }}
+          rsync -avz --no-times --delete --include-from='.rsync-include' --exclude='*' ./ ${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:${{ env.SSH_ROOT }}
 
       - name: ⚙️ Activate/Deactivate Plugins
         continue-on-error: true
